# Generated by Django 4.2.3 on 2023-09-21 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
